#!/bin/bash
#Energies.sh

# Original script
# 	author: Steven Pellizzeri <spelliz (at) clemson (dot) edu>
#	creation date: July 13, 2015

# Purpose: To compile the Energy and Thermodynamically corrected
#	   energies from Gaussian output in an space delimited list
#	   importable to excel

# Updates: 
#	July 15, 2015:
#	Added an array to search for info files from MIX runs and fixed
#	array generation to ignore files in old run folders
#	
#	July 22, 2015:
#	Added printing of the number of imaginary frequencies to Energies.txt
#
#	January 15, 2016:
#	Added support for ONIOM calculations

# Removes previous Energies output file if it exists
if [ -f Energies.txt ]; then 
	rm Energies.txt
	echo "Removed old version"
fi

# Find the .info files generated by info.sh and generates an array of filenames
#arr=( $(find . -maxdepth 4 -iname "*.info" -printf '%P\n' | grep -v -e run -e NOT_NEEDED -e LOGFILES))
arr=( $(find . -iname "*.info" -printf '%P\n' | grep -v -e run -e NOT_NEEDED -e LOGFILES))
#arr2=( $(find . -name "*s.info" -printf '%P\n'| grep -v -e run -e NOT_NEEDED -e LOGFILES))
#arr3=( $(find . -iname "*RO.info" -printf '%P\n'| grep -v -e run -e NOT_NEEDED -e LOGFILES))
#arr4=( $(find . -iname "*MIX.info" -printf '%P\n' | grep -v -e run -e NOT_NEEDED -e LOGFILES))
#arr5=( $(find . -iname "*SPE.info" -printf '%P\n' | grep -v -e run -e NOT_NEEDED -e LOGFILES))

s_arr=( "${arr[@]}" ) #"${arr2[@]}" "${arr3[@]}" "${arr4[@]}" "${arr5[@]}")

# Create the Header for Energies.txt
echo "FILENAME ENERGY ZPE H.CORR G.CORR Entropy #IMAG Charge/Multiplicity Stability S**2 Freq." >> Energies.txt

# Compiles and calculates the thermodyamic corrected energies and appends them to Energies.txt
for FILE in ${s_arr[@]}; do
	NAME=$(basename $FILE .info) # Filename

	if grep -q "ONIOM" $FILE; then
		ENERGY=$(grep -i "ONIOM: extrapolated energy" $FILE | tail -1 | grep -o '[-][0-9]*.[0-9]*') # Electronic Energy
	else 
		ENERGY=$(grep -i "scf done" $FILE | tail -1 | grep -o '[-][0-9]*.[0-9]*') # Electronic Energy
	fi

	ZPE=$(grep -i "Zero-point correction" $FILE | grep -o -e '[0-9].[0-9]*') # Zero-point Energy Correction
	ENTHALPY=$(grep "Thermal correction to Enthalpy" $FILE | grep -o '[0-9].[0-9]*') # Enthalpy Correction
	GIBBS=$(grep "Thermal correction to Gibbs Free Energy" $FILE | grep -o -e '[0-9].[0-9]*' -e '[-][0-9].[0-9]*') # Gibbs Energy Correction
	ENTROPY=$(grep "Total" $FILE | grep -o -e "[0-9]\{1,3\}.[0-9]*" | tail -1) # Entropy
	SPIN=$(grep -iA 1 "Contamination---" $FILE | grep -o -e '[0-9]\{1,2\}'.[0-9]* -e "Singlet" | tail -1) # S**2
	CM=$(grep -o -e '[0-9][,][0-9]' $FILE | head -1) # Charge , Multiplicity
        
        if grep -q "RHF -> UHF" $FILE; then # Stability Check Results
                STABLE=$(echo "RHF->UHF")
        else
            	if grep -q "internal" $FILE; then
                        STABLE=$(echo "internal")
                else
                    	if grep -q "stable" $FILE; then
				STABLE=$(echo "stable")
			else
				STABLE=$(echo "N/A")
			fi
                fi
        fi

#	if [[ "$STABLE" == "ERROR" ]]; then
#		if grep -q "ONIOM" $FILE; then
#			STABLE=$(echo "N/A")
#		fi
#	fi
        
        if grep -q "Imaganary Frequencies =" $FILE; then # Imaginary Frequency Check
        	FREQ=$(grep "Imaganary Frequencies =" $FILE | grep -o [0-9])
        else
        	FREQ=$(echo "0")
        fi
        
	T_ZPE=$(echo "$ZPE + $ENERGY" | bc -l) # Electronic + ZPE Energy
	T_ENTHALPY=$(echo "$ENTHALPY + $ENERGY" | bc -l) # Electronic + Enthalpy Energy
	T_GIBBS=$(echo "$GIBBS + $ENERGY" | bc -l) # Electronic + Gibbs Energy
	
	Freq_list=$(grep "^[[]" $FILE )

	if grep -q Error $FILE; then
		echo  $NAME' ERROR ERROR ERROR ERROR ERROR ERROR '$CM' ERROR ERROR ERROR' >> Energies_tmp.txt # In case of Error
	else
		echo $NAME' '$ENERGY' '$T_ZPE' '$T_ENTHALPY' '$T_GIBBS' '$ENTROPY' '$FREQ' '$CM' '$STABLE' '$SPIN' '$Freq_list >> Energies_tmp.txt # Print line to Energies.txt
	fi
done



# sorts and removes temp. Energies.txt
sort Energies_tmp.txt -o Energies_tmp.txt
cat Energies_tmp.txt >> Energies.txt
rm Energies_tmp.txt
